#!/usr/bin/env bash

# rainyday
# Version: 1.0.0
# Author: Michael Auderer
# Github Profile: https://github.com/auderer
# Project Repository: https://github.com/auderer/rainyday

RAINYDPATH=${RAINYDPATH:-"$HOME/.config/rainyd"}

if pgrep -f rainydplayer > /dev/null
then
  pkill -f rainydplayer &
  echo "Toggled rain off."
else 
  exec -a rainydplayer mpg123 -l 0 $RAINYDPATH/sounds/rain.mp3 &
  echo "Toggled rain on."
fi